### ISSUE TITLE
Xcode14 _clockHandRotationEffect 不支持

### ISSUE THREAD

**Issue by bigsen** [everettjf/ScriptWidget#1]
不知道有什么办法能够在 xcode14 上支持调用 _clockHandRotationEffect 方法不？

**Comment by everettjf** [comment]
是的。还没找到方法

**Comment by JohnnyHooo** [comment]
有知道的人吗

**Comment by Jdb156158** [comment]
大家都是为了做在widget上动画吗？可以加我微信15570666506，大家交流一下

**Comment by everettjf** [comment]
Yes, use Xcode13 and Swift to build a static library. Then call the methods exposed by the static library from Xcode14.

**Comment by everettjf** [comment]
Example : https://github.com/everettjf/Xcode13ClockHandRotationEffectModifier

**Comment by asdqian** [comment]
> 这个API目前会被苹果审核检查出来，有大佬有什么绕过的手段吗

会被拒审吗
